
#  开发环境（本机）
server:
  port: 1111
  context-path: /sso

# 配置注册中心
eureka:
  host: discovery-eureka
  client:
    serviceUrl:
      defaultZone: http://admin:psw@${discovery-eureka}:8761/eureka/  # 指定注册中心的地址
  instance:
    preferIpAddress: true
#    hostname : discovery   # 指定主机名时候通过主机名访问,否则通过ip地址
spring:
  application:
    name: taotao-sso-provider    # 项目名称尽量用小写

data:
  spring:
    datasource:
      url: jdbc:mysql://dbserver:3306/taotao-new?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true
      username: root
      password: 123
      driverClassName: com.mysql.jdbc.Driver
       # 参数
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR

