# taotao-oss-provider
server:
  port: 8000
  servlet-path: /
eureka:
  client:
    serviceUrl:
      defaultZone: http://ekserver:8761/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true
#    hostname : discovery   # 指定主机名时候通过主机名访问,否则通过ip地址
spring:
  application:
    name: taotao-oss-provider    # 项目名称尽量用小写

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
