server:
  port: 3333
  context-path: /oss

spring:
  application:
    name: taotao-oss-provider    # 项目名称尽量用小写

# 配置注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-eureka:8761/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true
#    hostname : discovery   # 指定主机名时候通过主机名访问,否则通过ip地址
