#

ali:
  oss:
    policy:
      expire: 300
    endpoint: oss-cn-shanghai.aliyuncs.com
    internal: oss-cn-shanghai-internal.aliyuncs.com  #这样的文件格式会报错。
    maxSize: 10
    accessKeySecret:
    accessKeyId:
    bucketName: shuzheng
    callback: http://shuzheng.tunnel.qydev.com/aliyun/oss/callback






